// Flat list of all calculators — used by the search and favorites features.
// IDs MUST match exactly: `${calcPrefix}-${tab.id}` as generated by CalcPage.

export const ALL_CALCULATORS = [
  // ── Spinning (calcPrefix="sp") ────────────────────────────────────────────
  { id: 'sp-count',      page: '/spinning', tabId: 'count',      category: 'spinning', bn: 'কাউন্ট কনভার্সন',            en: 'Count Conversion' },
  { id: 'sp-twist',      page: '/spinning', tabId: 'twist',      category: 'spinning', bn: 'টুইস্ট (TPI & TF)',            en: 'Twist (TPI & TF)' },
  { id: 'sp-strength',   page: '/spinning', tabId: 'strength',   category: 'spinning', bn: 'স্ট্রেনথ (RKM & CSP)',          en: 'Strength (RKM & CSP)' },
  { id: 'sp-production', page: '/spinning', tabId: 'production', category: 'spinning', bn: 'প্রডাকশন ও হাংক',               en: 'Production & Hank' },
  { id: 'sp-quality',    page: '/spinning', tabId: 'quality',    category: 'spinning', bn: 'ড্রাফট, ব্লেন্ড ও ওয়েস্ট',   en: 'Draft, Blend & Waste' },

  // ── Weaving (calcPrefix="wv") ─────────────────────────────────────────────
  { id: 'wv-gsm',        page: '/weaving',  tabId: 'gsm',        category: 'weaving',  bn: 'জিএসএম ও কভার ফ্যাক্টর',        en: 'GSM & Cover Factor' },
  { id: 'wv-dimension',  page: '/weaving',  tabId: 'dimension',  category: 'weaving',  bn: 'ওয়ার্প, ওয়েফট ও মাপ',          en: 'Warp, Weft & Dimensions' },
  { id: 'wv-efficiency', page: '/weaving',  tabId: 'efficiency', category: 'weaving',  bn: 'এফিশিয়েন্সি ও প্রডাকশন',        en: 'Efficiency & Production' },

  // ── Knitting (calcPrefix="kn") ────────────────────────────────────────────
  { id: 'kn-gsm',        page: '/knitting', tabId: 'gsm',        category: 'knitting', bn: 'জিএসএম ও স্টিচ লেংথ',            en: 'GSM & Stitch Length' },
  { id: 'kn-production', page: '/knitting', tabId: 'production', category: 'knitting', bn: 'প্রডাকশন ও কনসাম্পশন',            en: 'Production & Consumption' },
  { id: 'kn-fabric',     page: '/knitting', tabId: 'fabric',     category: 'knitting', bn: 'ফ্যাব্রিক প্রপার্টি',               en: 'Fabric Properties' },

  // ── Dyeing (calcPrefix="dy") ──────────────────────────────────────────────
  { id: 'dy-liquor',     page: '/dyeing',   tabId: 'liquor',     category: 'dyeing',   bn: 'লিকার রেশিও ও লবণ',               en: 'Liquor Ratio & Salt' },
  { id: 'dy-chemical',   page: '/dyeing',   tabId: 'chemical',   category: 'dyeing',   bn: 'কেমিক্যাল ডোজিং',                 en: 'Chemical Dosing' },
  { id: 'dy-recipe',     page: '/dyeing',   tabId: 'recipe',     category: 'dyeing',   bn: 'রেসিপি স্কেলিং ও ব্যাচ',           en: 'Recipe Scaling & Batch' },

  // ── Garments (calcPrefix="gm") ────────────────────────────────────────────
  { id: 'gm-efficiency',  page: '/garments', tabId: 'efficiency',  category: 'garments', bn: 'লাইন ও অপারেটর এফিশিয়েন্সি',    en: 'Line & Operator Efficiency' },
  { id: 'gm-consumption', page: '/garments', tabId: 'consumption', category: 'garments', bn: 'ফ্যাব্রিক কনসাম্পশন ও মার্কার',   en: 'Fabric Consumption & Marker' },
  { id: 'gm-target',      page: '/garments', tabId: 'target',      category: 'garments', bn: 'টার্গেট, কস্ট ও WIP',              en: 'Targets, Cost & WIP' },

  // ── TTQC (calcPrefix="tt") ────────────────────────────────────────────────
  { id: 'tt-aql',         page: '/ttqc',     tabId: 'aql',         category: 'ttqc',     bn: 'AQL স্যাম্পলিং',                   en: 'AQL Sampling' },
  { id: 'tt-defect',      page: '/ttqc',     tabId: 'defect',      category: 'ttqc',     bn: 'ডিফেক্ট মেট্রিক্স',               en: 'Defect Metrics' },
  { id: 'tt-quality',     page: '/ttqc',     tabId: 'quality',     category: 'ttqc',     bn: 'কোয়ালিটি মেট্রিক্স',              en: 'Quality Metrics' },
  { id: 'tt-fabric',      page: '/ttqc',     tabId: 'fabric',      category: 'ttqc',     bn: 'ফ্যাব্রিক টেস্ট',                  en: 'Fabric Tests' },

  // ── Converter (calcPrefix="co") ───────────────────────────────────────────
  { id: 'co-length',      page: '/converter', tabId: 'length',      category: 'converter', bn: 'দৈর্ঘ্য রূপান্তর',               en: 'Length Converter' },
  { id: 'co-weight',      page: '/converter', tabId: 'weight',      category: 'converter', bn: 'ওজন রূপান্তর',                 en: 'Weight Converter' },
  { id: 'co-count',       page: '/converter', tabId: 'count',       category: 'converter', bn: 'কাউন্ট রূপান্তর',               en: 'Yarn Count Converter' },
  { id: 'co-temperature', page: '/converter', tabId: 'temperature', category: 'converter', bn: 'তাপমাত্রা রূপান্তর',            en: 'Temperature Converter' },
];
