// TexCalc i18n — add a new language by adding a key block below
export const translations = {

  // ────────────────── BANGLA ────────────────────────────────────────────────
  bn: {
    // App
    appName:     'TexCalc',
    appTagline:  'টেক্সটাইল ইঞ্জিনিয়ারিং ক্যালকুলেটর',
    langToggle:  'EN',
    menu:        'মেনু',

    // Sidebar / Nav
    home:        'হোম',
    spinning:    'স্পিনিং',
    weaving:     'উইভিং',
    knitting:    'নিটিং',
    dyeing:      'ডাইং',
    garments:    'গার্মেন্টস',
    ttqc:        'টি.টি.কিউ.সি',
    converter:   'কনভার্টার',

    // Home
    heroTitle:      'টেক্সটাইল ইঞ্জিনিয়ারিং ক্যালকুলেটর',
    heroSubtitle:   'স্পিনিং, উইভিং, নিটিং, ডাইং, গার্মেন্টস ও কোয়ালিটি কন্ট্রোলের পেশাদার ক্যালকুলেটর',
    heroNote:       'বাংলাদেশের টেক্সটাইল পেশাদারদের জন্য তৈরি',
    categoriesTitle:'বিভাগসমূহ',
    spinningDesc:   'কাউন্ট, টুইস্ট, স্ট্রেনথ ও প্রডাকশন ক্যালকুলেটর',
    weavingDesc:    'জিএসএম, রিড, ওজন, এফিশিয়েন্সি ও প্রডাকশন',
    knittingDesc:   'জিএসএম, স্টিচ, প্রডাকশন ও টাইটনেস ফ্যাক্টর',
    dyeingDesc:     'লিকার রেশিও, কেমিক্যাল ডোজিং ও রেসিপি স্কেলিং',
    garmentsDesc:   'এফিশিয়েন্সি, কনসাম্পশন, টার্গেট ও কস্টিং',
    ttqcDesc:       'AQL, ডিফেক্ট রেট, DHU ও কোয়ালিটি মেট্রিক্স',
    converterDesc:  'দৈর্ঘ্য, ওজন, সুতার কাউন্ট ও তাপমাত্রা রূপান্তরকারী',

    // Search
    searchPlaceholder: 'ক্যালকুলেটর খুঁজুন…',
    noResults:         'কোনো ফলাফল পাওয়া যায়নি',

    // History
    historyTitle:   'সাম্প্রতিক হিসাব',
    noHistory:      'এখনো কোনো হিসাব নেই',
    clearHistory:   'মুছুন',
    savedAt:        'সংরক্ষিত',

    // Favorites
    favoritesTitle: 'প্রিয় ক্যালকুলেটর',
    noFavorites:    'এখনো কোনো প্রিয় নেই',
    addFavorite:    'প্রিয়তে যোগ করুন',
    removeFavorite: 'প্রিয় থেকে সরান',

    // Common UI
    inputs:       'ইনপুট',
    result:       'ফলাফল',
    formula:      'সূত্র',
    reset:        'রিসেট',
    copy:         'কপি',
    copied:       'কপি হয়েছে!',
    enterValue:   'মান লিখুন',
    invalidInput: 'সঠিক মান দিন',
    bidirectionalHint: 'যেকোনো একটি ফিল্ডে মান লিখুন — বাকিগুলো স্বয়ংক্রিয়ভাবে গণনা হবে',

    // ── Spinning ──────────────────────────────────────────────────────────
    spinningTitle:  'স্পিনিং ক্যালকুলেটর',
    spinningDesc2:  'কাউন্ট কনভার্সন, টুইস্ট, স্ট্রেনথ, প্রডাকশন ও কোয়ালিটি',

    countConversion:  'কাউন্ট কনভার্সন',
    twistTab:         'টুইস্ট',
    strengthTab:      'স্ট্রেনথ',
    productionTab:    'প্রডাকশন',
    qualityTab:       'কোয়ালিটি',

    neLabel:          'Ne কাউন্ট',
    texLabel:         'Tex',
    denierLabel:      'Denier',
    nmLabel:          'Nm',

    tpi:              'টুইস্ট পার ইঞ্চি (TPI)',
    twistFactor:      'টুইস্ট ফ্যাক্টর',
    countNe:          'কাউন্ট (Ne)',
    tpiInput:         'TPI',
    tfInput:          'টুইস্ট ফ্যাক্টর',
    tpiResult:        'TPI মান',
    tfResult:         'টুইস্ট ফ্যাক্টর',

    yarnRKM:          'ইয়ার্ন RKM',
    csp:              'CSP',
    strength:         'স্ট্রেনথ (cN/tex)',
    countForStrength: 'কাউন্ট (Ne)',
    rkmResult:        'RKM মান',
    cspResult:        'CSP মান',

    prodSpindle:      'প্রডাকশন/স্পিন্ডেল',
    hankToKg:         'হাংক থেকে কেজি',
    bobbinWeight:     'ববিন ওজন',
    hank:             'হাংক',
    speedRPM:         'গতি (RPM)',
    efficiency:       'এফিশিয়েন্সি (%)',
    hanks:            'হাংক সংখ্যা',
    count:            'কাউন্ট (Ne)',
    bobbinLength:     'সুতার দৈর্ঘ্য (গজ)',
    prodResult:       'প্রডাকশন (হাংক/দিন)',
    hankKgResult:     'ওজন (কেজি)',
    bobbinGResult:    'ববিন ওজন (গ্রাম)',

    draft:            'ড্রাফট',
    rovingHank:       'রোভিং হাংক',
    blendRatio:       'ব্লেন্ড রেশিও',
    yarnRealisation:  'ইয়ার্ন রিয়ালাইজেশন',
    feedCount:        'ফিড কাউন্ট',
    deliveryCount:    'ডেলিভারি কাউন্ট',
    rovingWeightG:    'রোভিং ওজন (গ্রাম)',
    rovingLengthYd:   'রোভিং দৈর্ঘ্য (গজ)',
    fiberAWeight:     'ফাইবার A ওজন (কেজি)',
    totalWeight:      'মোট ওজন (কেজি)',
    inputWeightKg:    'ইনপুট ওজন (কেজি)',
    outputWeightKg:   'আউটপুট ওজন (কেজি)',
    draftResult:      'ড্রাফট',
    rovingResult:     'রোভিং হাংক',
    blendResult:      'ব্লেন্ড রেশিও (%)',
    realisationResult:'ইয়ার্ন রিয়ালাইজেশন (%)',
    wasteResult:      'ওয়েস্ট (%)',

    // ── Weaving ───────────────────────────────────────────────────────────
    weavingTitle:   'উইভিং ক্যালকুলেটর',
    weavingDesc2:   'জিএসএম, রিড, কভার, ওজন, এফিশিয়েন্সি ও প্রডাকশন',

    gsmCoverTab:    'জিএসএম ও কভার',
    dimensionTab:   'ডাইমেনশন ও ওজন',
    effProdTab:     'এফিশিয়েন্সি ও প্রডাকশন',

    gsmCalc:        'জিএসএম ক্যালকুলেশন',
    reedCount:      'রিড কাউন্ট',
    coverFactor:    'কভার ফ্যাক্টর',
    epi:            'EPI (প্রতি ইঞ্চিতে তার)',
    ppi:            'PPI (প্রতি ইঞ্চিতে পিক)',
    warpCount:      'ওয়ার্প কাউন্ট (Ne)',
    weftCount:      'ওয়েফট কাউন্ট (Ne)',
    crimpFactor:    'ক্রিম্প ফ্যাক্টর',
    endsPerDent:    'প্রতি ডেন্টে সুতা',
    gsmResult:      'জিএসএম',
    reedResult:     'রিড কাউন্ট',
    coverResult:    'কভার ফ্যাক্টর',

    clothWidth:     'কাপড়ের প্রস্থ',
    warpLength:     'ওয়ার্প দৈর্ঘ্য',
    warpWeightKg:   'ওয়ার্প ওজন (কেজি)',
    weftWeightKg:   'ওয়েফট ওজন (কেজি)',
    epiFromReed:    'রিড থেকে EPI',
    crimpPct:       'ক্রিম্প %',
    fabricShrinkage:'কাপড় সংকোচন',
    totalEnds:      'মোট এন্ড সংখ্যা',
    pieceLength:    'পিস দৈর্ঘ্য (গজ)',
    pieceAllowance: 'অ্যালাউন্স (গজ)',
    numPieces:      'পিস সংখ্যা',
    widthInches:    'প্রস্থ (ইঞ্চি)',
    lengthYards:    'দৈর্ঘ্য (গজ)',
    yarnLengthCm:   'সুতার দৈর্ঘ্য (cm)',
    fabricLengthCm: 'কাপড়ের দৈর্ঘ্য (cm)',
    beforeLength:   'আগের দৈর্ঘ্য',
    afterLength:    'পরের দৈর্ঘ্য',
    clothWidthResult:'কাপড়ের প্রস্থ (ইঞ্চি)',
    warpLenResult:  'ওয়ার্প দৈর্ঘ্য (গজ)',
    warpWtResult:   'ওয়ার্প ওজন (কেজি)',
    weftWtResult:   'ওয়েফট ওজন (কেজি)',
    epiResult:      'EPI',
    crimpResult:    'ক্রিম্প (%)',
    shrinkResult:   'সংকোচন (%)',

    loomEfficiency:    'লুম এফিশিয়েন্সি',
    productionMeterDay:'প্রডাকশন (মিটার/দিন)',
    warpBeam:          'ওয়ার্প বিম সংখ্যা',
    picksPerMinute:    'পিকস পার মিনিট',
    actualProd:        'প্রকৃত প্রডাকশন',
    targetProd:        'লক্ষ্য প্রডাকশন',
    ppm:               'PPM (পিকস/মিনিট)',
    hoursPerDay:       'ঘণ্টা/দিন',
    creelCapacity:     'ক্রিল ক্যাপাসিটি',
    loomEffResult:     'এফিশিয়েন্সি (%)',
    prodMResult:       'প্রডাকশন (মিটার)',
    beamCountResult:   'বিম সংখ্যা',
    ppmResult:         'পিকস/মিনিট',

    // ── Knitting ──────────────────────────────────────────────────────────
    knittingTitle:  'নিটিং ক্যালকুলেটর',
    knittingDesc2:  'জিএসএম, স্টিচ, প্রডাকশন, টাইটনেস ও আরও অনেক',

    gsmStitchTab:   'জিএসএম ও স্টিচ',
    productionKTab: 'প্রডাকশন',
    fabricTab:      'ফ্যাব্রিক',

    gsmKnit:        'জিএসএম (নিটিং)',
    stitchLength:   'স্টিচ লেংথ',
    loopDensity:    'লুপ ডেনসিটি',
    wpi:            'WPI (Wales Per Inch)',
    cpi:            'CPI (Courses Per Inch)',
    sl:             'স্টিচ লেংথ (cm)',
    tex:            'সুতার Tex',
    gsmKnitResult:  'জিএসএম',
    slResult:       'স্টিচ লেংথ (cm)',
    loopResult:     'লুপ ডেনসিটি',

    yarnConsumptionK:  'ইয়ার্ন কনসাম্পশন',
    productionKgShift: 'প্রডাকশন (কেজি/শিফট)',
    fabricKgWeight:    'কাপড়ের ওজন (কেজি)',
    wastePctK:         'ওয়েস্ট (%)',
    rpmK:              'RPM',
    feeders:           'ফিডার সংখ্যা',
    slCm:              'স্টিচ লেংথ (cm)',
    texK:              'সুতার Tex',
    hoursShift:        'ঘণ্টা/শিফট',
    yarnConsResult:    'ইয়ার্ন কনসাম্পশন (কেজি)',
    prodKgResult:      'প্রডাকশন (কেজি)',

    shrinkageAllowance:  'সংকোচন অ্যালাউন্স',
    fabricWidthCylinder: 'সিলিন্ডার থেকে প্রস্থ',
    tightnessFactor:     'টাইটনেস ফ্যাক্টর',
    yarnCountFromGSM:    'GSM থেকে ইয়ার্ন কাউন্ট',
    finalWidth:          'ফিনিশড প্রস্থ (ইঞ্চি)',
    shrinkagePctK:       'সংকোচন (%)',
    cylinderDia:         'সিলিন্ডার ব্যাস (ইঞ্চি)',
    gaugeAdj:            'গেজ অ্যাডজাস্টমেন্ট',
    slTF:                'স্টিচ লেংথ (cm)',
    texTF:               'সুতার Tex',
    gsmForCount:         'জিএসএম',
    wpiForCount:         'WPI',
    cpiForCount:         'CPI',
    slForCount:          'স্টিচ লেংথ (cm)',
    shrinkAllowResult:   'প্রয়োজনীয় প্রস্থ (ইঞ্চি)',
    fabricWidthResult:   'ফ্যাব্রিক প্রস্থ (ইঞ্চি)',
    texFromGSMResult:    'সুতার Tex',
    neFromGSMResult:     'সুতার Ne',

    // ── Dyeing ────────────────────────────────────────────────────────────
    dyeingTitle:    'ডাইং ক্যালকুলেটর',
    dyeingDesc2:    'লিকার রেশিও, কেমিক্যাল ডোজিং, রেসিপি স্কেলিং ও আরও অনেক',

    liquorRatioTab: 'লিকার রেশিও',
    chemicalTab:    'কেমিক্যাল',
    recipeTab:      'রেসিপি ও ব্যাচ',

    waterVolume:    'পানির পরিমাণ',
    liquorRatioCalc:'লিকার রেশিও',
    dilutionCalc:   'ডাইলিউশন',
    winchVolume:    'উইঞ্চ ভলিউম',
    fabricWeightKg: 'কাপড় (কেজি)',
    liquorRatioIn:  'লিকার রেশিও',
    totalWaterL:    'মোট পানি (লিটার)',
    stockVolMl:     'স্টক ভলিউম (mL)',
    stockConc:      'স্টক ঘনত্ব (g/L)',
    targetConc:     'টার্গেট ঘনত্ব (g/L)',
    winchLength:    'উইঞ্চের দৈর্ঘ্য (m)',
    winchDia:       'উইঞ্চের ব্যাস (m)',
    waterResult:    'পানির পরিমাণ (লিটার)',
    dilutionResult: 'চূড়ান্ত ভলিউম (mL)',
    winchVolResult: 'উইঞ্চ ভলিউম (L)',
    lrResult:       'লিকার রেশিও',

    chemConc:       'কেমিক্যাল ঘনত্ব',
    dosingML:       'ডোজিং (mL)',
    saltDosage:     'লবণের পরিমাণ',
    auxiliaryKg:    'অক্সিলিয়ারি (কেজি)',
    chemDosingLR:   'কেমিক্যাল ডোজিং (LR)',
    density:        'ঘনত্ব (g/mL)',
    owfPct:         'OWF% (%)',
    fabricForOwf:   'কাপড় (কেজি)',
    fabricSalt:     'কাপড় (কেজি)',
    shadePercent:   'শেড % (%)',
    auxOWF:         'OWF% (%)',
    batchKg:        'ব্যাচ (কেজি)',
    chemicalGram:   'কেমিক্যাল (গ্রাম)',
    chemPercent:    'কেমিক্যাল (%)',
    fabricKg:       'কাপড় (কেজি)',
    totalWater:     'মোট পানি (লিটার)',
    concResult:     'ঘনত্ব (g/L)',
    dosingResult:   'ডোজিং (mL)',
    saltResult:     'লবণ (কেজি)',
    auxKgResult:    'অক্সিলিয়ারি (কেজি)',
    chemResult:     'কেমিক্যাল (গ্রাম)',

    dyeQuantity:    'ডাই পরিমাণ',
    scouringBath:   'স্কাওয়ারিং বাথ',
    stripedRecalc:  'স্ট্রাইপড রেসিপি',
    washingEff:     'ওয়াশিং এফিশিয়েন্সি',
    tempDiff:       'তাপমাত্রার পার্থক্য',
    dyeOWF:         'ডাই OWF% (%)',
    fabricWeight:   'কাপড় (কেজি)',
    scourConc:      'স্কাওয়ারিং ঘনত্ব (g/L)',
    dye1Pct:        'ডাই ১ (%)',
    dye2Pct:        'ডাই ২ (%)',
    totalFabric:    'মোট কাপড় (কেজি)',
    initialDye:     'প্রাথমিক ডাই (g/L)',
    finalDye:       'চূড়ান্ত ডাই (g/L)',
    initTemp:       'প্রাথমিক তাপমাত্রা (°C)',
    finalTemp:      'চূড়ান্ত তাপমাত্রা (°C)',
    dyeQtyResult:   'ডাই পরিমাণ (কেজি)',
    scourResult:    'স্কাওয়ারিং এজেন্ট (গ্রাম)',
    dye1Result:     'ডাই ১ (কেজি)',
    dye2Result:     'ডাই ২ (কেজি)',
    washEffResult:  'ওয়াশিং এফিশিয়েন্সি (%)',
    tempDiffResult: 'তাপমাত্রার পার্থক্য (°C)',

    // ── Garments ──────────────────────────────────────────────────────────
    garmentsTitle:  'গার্মেন্টস ক্যালকুলেটর',
    garmentsDesc2:  'এফিশিয়েন্সি, কনসাম্পশন, টার্গেট, কস্টিং ও আরও অনেক',

    lineEfficiencyTab: 'এফিশিয়েন্সি',
    consumptionTab:    'কনসাম্পশন',
    targetTab:         'টার্গেট',

    lineEfficiency:    'লাইন এফিশিয়েন্সি',
    piecesPerHour:     'পিস/ঘন্টা',
    operatorEfficiency:'অপারেটর এফিশিয়েন্সি',
    lineCapacity:      'লাইন ক্যাপাসিটি',
    totalSMV:          'মোট উৎপাদিত SMV',
    workers:           'কর্মী সংখ্যা',
    minutes:           'মিনিট (শিফট)',
    targetEff:         'টার্গেট এফিশিয়েন্সি (%)',
    actualPcs:         'প্রকৃত পিস',
    targetPcs:         'লক্ষ্য পিস',
    hoursDay:          'ঘণ্টা/দিন',
    effResult:         'এফিশিয়েন্সি (%)',
    opEffResult:       'অপারেটর এফিশিয়েন্সি (%)',
    lineCapResult:     'লাইন ক্যাপাসিটি (পিস/দিন)',

    fabricConsumption: 'ফ্যাব্রিক কনসাম্পশন',
    cmtCost:           'CMT কস্ট',
    cmCost:            'CM কস্ট',
    fabricReqYards:    'ফ্যাব্রিক রিকোয়্যারমেন্ট',
    length:            'দৈর্ঘ্য (cm)',
    width:             'প্রস্থ (cm)',
    allowance:         'অ্যালাউন্স (cm)',
    gsm:               'জিএসএম',
    cuttingCost:       'কাটিং কস্ট (৳)',
    sewingCost:        'সেলাই কস্ট (৳)',
    finishCost:        'ফিনিশিং কস্ট (৳)',
    fabricCost:        'ফ্যাব্রিক কস্ট (৳)',
    labourCost:        'শ্রম খরচ (৳)',
    overheadCost:      'ওভারহেড খরচ (৳)',
    profitPct:         'লাভ (%)',
    qtyPcs:            'পরিমাণ (পিস)',
    gsmForFabReq:      'জিএসএম',
    widthYards:        'প্রস্থ (ইঞ্চি)',
    consumResult:      'কনসাম্পশন (কেজি)',
    cmtResult:         'CMT খরচ (৳)',
    cmResult:          'মোট খরচ (৳)',
    fabReqResult:      'ফ্যাব্রিক দরকার (গজ)',
    smv:               'SMV (মিনিট)',
    piecesResult:      'পিস/ঘন্টা',

    dailyTarget:       'দৈনিক টার্গেট',
    netProfit:         'নেট লাভ',
    attendancePct:     'উপস্থিতি %',
    minutesProduced:   'মিনিট প্রডাকশন',
    salePrice:         'বিক্রয় মূল্য (৳)',
    costPrice:         'ক্রয় মূল্য (৳)',
    presentWorkers:    'উপস্থিত কর্মী',
    totalWorkers:      'মোট কর্মী',
    piecesProduced:    'উৎপাদিত পিস',
    dailyTgtResult:    'দৈনিক টার্গেট (পিস)',
    netProfitResult:   'নেট লাভ (%)',
    attResult:         'উপস্থিতি (%)',
    minsProdResult:    'মিনিট প্রডাকশন',

    // ── TTQC ──────────────────────────────────────────────────────────────
    ttqcTitle:   'টি.টি.কিউ.সি ক্যালকুলেটর',
    ttqcDesc2:   'AQL স্যাম্পলিং, ডিফেক্ট, কোয়ালিটি মেট্রিক্স ও ফ্যাব্রিক টেস্ট',

    defectTab:     'ডিফেক্ট',
    qualityQTab:   'কোয়ালিটি',
    fabricQTab:    'ফ্যাব্রিক',

    aqlCalc:      'AQL স্যাম্পলিং',
    defectRate:   'ডিফেক্ট রেট',
    dhuCalc:      'DHU ক্যালকুলেশন',
    lotSize:      'লট সাইজ',
    aqlLevel:     'AQL লেভেল',
    inspLevel:    'ইন্সপেকশন লেভেল',
    sampleSize:   'স্যাম্পল সাইজ',
    acceptNum:    'গ্রহণযোগ্য সংখ্যা (Ac)',
    rejectNum:    'প্রত্যাখ্যাত সংখ্যা (Re)',
    defectivePcs: 'ডিফেক্টিভ পিস',
    totalInspected:'মোট পরীক্ষিত',
    totalDefects: 'মোট ডিফেক্ট',
    defectRateResult:'ডিফেক্ট রেট (%)',
    dhuResult:    'DHU',

    passRate:     'পাস রেট',
    passPcs:      'পাস পিস',
    totalPcs:     'মোট পিস',
    passRateResult:'পাস রেট (%)',

    weightedDHU:       'ওজনভিত্তিক DHU',
    criticalDefects:   'ক্রিটিক্যাল ডিফেক্ট',
    majorDefects:      'মেজর ডিফেক্ট',
    minorDefects:      'মাইনর ডিফেক্ট',
    usesInspectedCount:'পূর্বের ইন্সপেকশন সংখ্যা ব্যবহার',
    wDhuResult:        'ওজনভিত্তিক DHU',

    auditScore:        'অডিট স্কোর',
    defectsFound:      'পাওয়া ডিফেক্ট',
    possibleDefects:   'সম্ভাব্য ডিফেক্ট',
    auditResult:       'অডিট স্কোর (%)',

    dpmo:              'DPMO',
    sampleSizeDPMO:    'স্যাম্পল সাইজ',
    defectsFoundD:     'পাওয়া ডিফেক্ট',
    dpmoResult:        'DPMO',
    fpyResult:         'ফার্স্ট পাস ইয়েল্ড (%)',

    cpkCalc:           'Cpk ক্যালকুলেশন',
    sigmaLevel:        'সিগমা লেভেল',
    cpkResult:         'Cpk',

    pqCalc:            'PQ স্কোর',
    qualityPoint:      'কোয়ালিটি পয়েন্ট',
    quantityPoint:     'কোয়ান্টিটি পয়েন্ট',
    pqResult:          'PQ স্কোর',

    fabric4Point:      'ফ্যাব্রিক ৪-পয়েন্ট',
    totalPoints:       'মোট পেনাল্টি পয়েন্ট',
    yardInspected:     'পরীক্ষিত গজ',
    fp4Result:         'পয়েন্ট/১০০ গজ²',
    fp4GradeResult:    'গ্রেড',

    fabric4PointPer100m:'৪-পয়েন্ট প্রতি ১০০ মিটার',
    linearYards:        'রৈখিক গজ',
    fabricWidth:        'ফ্যাব্রিক প্রস্থ (ইঞ্চি)',
    fp100mResult:       'পয়েন্ট/১০০মি',

    fabricGradeGSM:    'GSM ভিত্তিক গ্রেড',
    gsmForGrade:        'জিএসএম',
    gsmGradeResult:    'গ্রেড',

    // ── Converter ──
    converterTitle:     'ইউনিট কনভার্টার',
    converterDesc2:     'দৈর্ঘ্য, ওজন, সুতার কাউন্ট ও তাপমাত্রা রূপান্তরকারী',
    lengthTab:          'দৈর্ঘ্য',
    weightTab:          'ওজন',
    countTab:           'সুতার কাউন্ট',
    tempTab:            'তাপমাত্রা',
    lengthTitle:        'দৈর্ঘ্য রূপান্তর',
    weightTitle:        'ওজন রূপান্তর',
    countTitle:         'সুতার কাউন্ট রূপান্তর',
    tempTitle:          'তাপমাত্রা রূপান্তর',
    inches:             'ইঞ্চি (in)',
    yards:              'গজ (yd)',
    meters:             'মিটার (m)',
    cm:                 'সেন্টিমিটার (cm)',
    kg:                 'কেজি (kg)',
    grams:              'গ্রাম (g)',
    lbs:                'পাউন্ড (lbs)',
    oz:                 'আউন্স (oz)',
    celsius:            'সেলসিয়াস (°C)',
    fahrenheit:         'ফারেনহাইট (°F)',
    kelvin:             'কেলভিন (K)',

    // Footer
    footerDev:      'ডেভেলপার: Md Rifat (mdrifatdev)',
    footerGithub:   'GitHub: github.com/mdrifatdev',
    footerMade:     'Made for Textile Engineers of Bangladesh 🇧🇩',
    footerVersion:  'v1.0.0',
  },

  // ────────────────── ENGLISH ───────────────────────────────────────────────
  en: {
    // App
    appName:     'TexCalc',
    appTagline:  'Textile Engineering Calculator',
    langToggle:  'বাং',
    menu:        'Menu',

    // Sidebar / Nav
    home:        'Home',
    spinning:    'Spinning',
    weaving:     'Weaving',
    knitting:    'Knitting',
    dyeing:      'Dyeing',
    garments:    'Garments',
    ttqc:        'TTQC',
    converter:   'Converter',

    // Home
    heroTitle:      'Textile Engineering Calculator',
    heroSubtitle:   'Professional calculators for Spinning, Weaving, Knitting, Dyeing, Garments & Quality Control',
    heroNote:       'Built for Textile Professionals of Bangladesh',
    categoriesTitle:'Categories',
    spinningDesc:   'Count, Twist, Strength & Production Calculators',
    weavingDesc:    'GSM, Reed, Weight, Efficiency & Production',
    knittingDesc:   'GSM, Stitch, Production & Tightness Factor',
    dyeingDesc:     'Liquor Ratio, Chemical Dosing & Recipe Scaling',
    garmentsDesc:   'Efficiency, Consumption, Targets & Costing',
    ttqcDesc:       'AQL, Defect Rate, DHU & Quality Metrics',
    converterDesc:  'Convert between units of length, weight, count, and temperature',

    // Search
    searchPlaceholder: 'Search calculators…',
    noResults:         'No results found',

    // History
    historyTitle:   'Recent Calculations',
    noHistory:      'No history yet',
    clearHistory:   'Clear',
    savedAt:        'Saved',

    // Favorites
    favoritesTitle: 'Favourite Calculators',
    noFavorites:    'No favourites yet',
    addFavorite:    'Add to favourites',
    removeFavorite: 'Remove from favourites',

    // Common UI
    inputs:       'Inputs',
    result:       'Result',
    formula:      'Formula',
    reset:        'Reset',
    copy:         'Copy',
    copied:       'Copied!',
    enterValue:   'Enter value',
    invalidInput: 'Enter valid values',
    bidirectionalHint: 'Type in any field — the others are calculated automatically',

    // ── Spinning ──────────────────────────────────────────────────────────
    spinningTitle:  'Spinning Calculator',
    spinningDesc2:  'Count Conversion, Twist, Strength, Production & Quality',

    countConversion:  'Count Conversion',
    twistTab:         'Twist',
    strengthTab:      'Strength',
    productionTab:    'Production',
    qualityTab:       'Quality',

    neLabel:          'Ne Count',
    texLabel:         'Tex',
    denierLabel:      'Denier',
    nmLabel:          'Nm',

    tpi:              'Twist Per Inch (TPI)',
    twistFactor:      'Twist Factor',
    countNe:          'Count (Ne)',
    tpiInput:         'TPI',
    tfInput:          'Twist Factor',
    tpiResult:        'TPI Value',
    tfResult:         'Twist Factor',

    yarnRKM:          'Yarn RKM',
    csp:              'CSP',
    strength:         'Strength (cN/tex)',
    countForStrength: 'Count (Ne)',
    rkmResult:        'RKM Value',
    cspResult:        'CSP Value',

    prodSpindle:      'Production/Spindle',
    hankToKg:         'Hank to Kg',
    bobbinWeight:     'Bobbin Weight',
    hank:             'Hank',
    speedRPM:         'Speed (RPM)',
    efficiency:       'Efficiency (%)',
    hanks:            'No. of Hanks',
    count:            'Count (Ne)',
    bobbinLength:     'Yarn Length (yards)',
    prodResult:       'Production (hanks/day)',
    hankKgResult:     'Weight (kg)',
    bobbinGResult:    'Bobbin Weight (g)',

    draft:            'Draft',
    rovingHank:       'Roving Hank',
    blendRatio:       'Blend Ratio',
    yarnRealisation:  'Yarn Realisation',
    feedCount:        'Feed Count',
    deliveryCount:    'Delivery Count',
    rovingWeightG:    'Roving Weight (g)',
    rovingLengthYd:   'Roving Length (yards)',
    fiberAWeight:     'Fiber A Weight (kg)',
    totalWeight:      'Total Weight (kg)',
    inputWeightKg:    'Input Weight (kg)',
    outputWeightKg:   'Output Weight (kg)',
    draftResult:      'Draft',
    rovingResult:     'Roving Hank',
    blendResult:      'Blend Ratio (%)',
    realisationResult:'Yarn Realisation (%)',
    wasteResult:      'Waste (%)',

    // ── Weaving ───────────────────────────────────────────────────────────
    weavingTitle:   'Weaving Calculator',
    weavingDesc2:   'GSM, Reed, Cover, Weight, Efficiency & Production',

    gsmCoverTab:    'GSM & Cover',
    dimensionTab:   'Dimensions & Weight',
    effProdTab:     'Efficiency & Production',

    gsmCalc:        'GSM Calculation',
    reedCount:      'Reed Count',
    coverFactor:    'Cover Factor',
    epi:            'EPI (Ends Per Inch)',
    ppi:            'PPI (Picks Per Inch)',
    warpCount:      'Warp Count (Ne)',
    weftCount:      'Weft Count (Ne)',
    crimpFactor:    'Crimp Factor',
    endsPerDent:    'Ends Per Dent',
    gsmResult:      'GSM',
    reedResult:     'Reed Count',
    coverResult:    'Cover Factor',

    clothWidth:     'Cloth Width',
    warpLength:     'Warp Length',
    warpWeightKg:   'Warp Weight (kg)',
    weftWeightKg:   'Weft Weight (kg)',
    epiFromReed:    'EPI from Reed',
    crimpPct:       'Crimp %',
    fabricShrinkage:'Fabric Shrinkage',
    totalEnds:      'Total Ends',
    pieceLength:    'Piece Length (yards)',
    pieceAllowance: 'Allowance (yards)',
    numPieces:      'Number of Pieces',
    widthInches:    'Width (inches)',
    lengthYards:    'Length (yards)',
    yarnLengthCm:   'Yarn Length (cm)',
    fabricLengthCm: 'Fabric Length (cm)',
    beforeLength:   'Before Length',
    afterLength:    'After Length',
    clothWidthResult:'Cloth Width (inches)',
    warpLenResult:  'Warp Length (yards)',
    warpWtResult:   'Warp Weight (kg)',
    weftWtResult:   'Weft Weight (kg)',
    epiResult:      'EPI',
    crimpResult:    'Crimp (%)',
    shrinkResult:   'Shrinkage (%)',

    loomEfficiency:    'Loom Efficiency',
    productionMeterDay:'Production (m/day)',
    warpBeam:          'Warp Beam Count',
    picksPerMinute:    'Picks Per Minute',
    actualProd:        'Actual Production',
    targetProd:        'Target Production',
    ppm:               'PPM (Picks/Min)',
    hoursPerDay:       'Hours/Day',
    creelCapacity:     'Creel Capacity',
    loomEffResult:     'Efficiency (%)',
    prodMResult:       'Production (meters)',
    beamCountResult:   'No. of Beams',
    ppmResult:         'Picks/Min',

    // ── Knitting ──────────────────────────────────────────────────────────
    knittingTitle:  'Knitting Calculator',
    knittingDesc2:  'GSM, Stitch, Production, Tightness & More',

    gsmStitchTab:   'GSM & Stitch',
    productionKTab: 'Production',
    fabricTab:      'Fabric',

    gsmKnit:        'GSM (Knitting)',
    stitchLength:   'Stitch Length',
    loopDensity:    'Loop Density',
    wpi:            'WPI (Wales Per Inch)',
    cpi:            'CPI (Courses Per Inch)',
    sl:             'Stitch Length (cm)',
    tex:            'Yarn Tex',
    gsmKnitResult:  'GSM',
    slResult:       'Stitch Length (cm)',
    loopResult:     'Loop Density',

    yarnConsumptionK:  'Yarn Consumption',
    productionKgShift: 'Production (kg/shift)',
    fabricKgWeight:    'Fabric Weight (kg)',
    wastePctK:         'Waste (%)',
    rpmK:              'RPM',
    feeders:           'No. of Feeders',
    slCm:              'Stitch Length (cm)',
    texK:              'Yarn Tex',
    hoursShift:        'Hours/Shift',
    yarnConsResult:    'Yarn Consumption (kg)',
    prodKgResult:      'Production (kg)',

    shrinkageAllowance:  'Shrinkage Allowance',
    fabricWidthCylinder: 'Fabric Width from Cylinder',
    tightnessFactor:     'Tightness Factor',
    yarnCountFromGSM:    'Yarn Count from GSM',
    finalWidth:          'Finished Width (inches)',
    shrinkagePctK:       'Shrinkage (%)',
    cylinderDia:         'Cylinder Diameter (inches)',
    gaugeAdj:            'Gauge Adjustment',
    slTF:                'Stitch Length (cm)',
    texTF:               'Yarn Tex',
    gsmForCount:         'GSM',
    wpiForCount:         'WPI',
    cpiForCount:         'CPI',
    slForCount:          'Stitch Length (cm)',
    shrinkAllowResult:   'Required Width (inches)',
    fabricWidthResult:   'Fabric Width (inches)',
    texFromGSMResult:    'Yarn Tex',
    neFromGSMResult:     'Yarn Ne',

    // ── Dyeing ────────────────────────────────────────────────────────────
    dyeingTitle:    'Dyeing Calculator',
    dyeingDesc2:    'Liquor Ratio, Chemical Dosing, Recipe Scaling & More',

    liquorRatioTab: 'Liquor Ratio',
    chemicalTab:    'Chemicals',
    recipeTab:      'Recipe & Batch',

    waterVolume:    'Water Volume',
    liquorRatioCalc:'Liquor Ratio',
    dilutionCalc:   'Dilution',
    winchVolume:    'Winch Volume',
    fabricWeightKg: 'Fabric (kg)',
    liquorRatioIn:  'Liquor Ratio',
    totalWaterL:    'Total Water (Liters)',
    stockVolMl:     'Stock Volume (mL)',
    stockConc:      'Stock Concentration (g/L)',
    targetConc:     'Target Concentration (g/L)',
    winchLength:    'Winch Length (m)',
    winchDia:       'Winch Diameter (m)',
    waterResult:    'Water Volume (Liters)',
    dilutionResult: 'Final Volume (mL)',
    winchVolResult: 'Winch Volume (L)',
    lrResult:       'Liquor Ratio',

    chemConc:       'Chemical Concentration',
    dosingML:       'Dosing (mL)',
    saltDosage:     'Salt Dosage',
    auxiliaryKg:    'Auxiliary (kg)',
    chemDosingLR:   'Chemical Dosing (LR)',
    density:        'Density (g/mL)',
    owfPct:         'OWF% (%)',
    fabricForOwf:   'Fabric (kg)',
    fabricSalt:     'Fabric (kg)',
    shadePercent:   'Shade % (%)',
    auxOWF:         'OWF% (%)',
    batchKg:        'Batch (kg)',
    chemicalGram:   'Chemical (grams)',
    chemPercent:    'Chemical (%)',
    fabricKg:       'Fabric (kg)',
    totalWater:     'Total Water (Liters)',
    concResult:     'Concentration (g/L)',
    dosingResult:   'Dosing (mL)',
    saltResult:     'Salt (kg)',
    auxKgResult:    'Auxiliary (kg)',
    chemResult:     'Chemical (grams)',

    dyeQuantity:    'Dye Quantity',
    scouringBath:   'Scouring Bath',
    stripedRecalc:  'Striped Recipe',
    washingEff:     'Washing Efficiency',
    tempDiff:       'Temperature Difference',
    dyeOWF:         'Dye OWF% (%)',
    fabricWeight:   'Fabric (kg)',
    scourConc:      'Scouring Concentration (g/L)',
    dye1Pct:        'Dye 1 (%)',
    dye2Pct:        'Dye 2 (%)',
    totalFabric:    'Total Fabric (kg)',
    initialDye:     'Initial Dye (g/L)',
    finalDye:       'Final Dye (g/L)',
    initTemp:       'Initial Temperature (°C)',
    finalTemp:      'Final Temperature (°C)',
    dyeQtyResult:   'Dye Quantity (kg)',
    scourResult:    'Scouring Agent (g)',
    dye1Result:     'Dye 1 (kg)',
    dye2Result:     'Dye 2 (kg)',
    washEffResult:  'Washing Efficiency (%)',
    tempDiffResult: 'Temperature Difference (°C)',

    // ── Garments ──────────────────────────────────────────────────────────
    garmentsTitle:  'Garments Calculator',
    garmentsDesc2:  'Efficiency, Consumption, Targets, Costing & More',

    lineEfficiencyTab: 'Efficiency',
    consumptionTab:    'Consumption',
    targetTab:         'Targets',

    lineEfficiency:    'Line Efficiency',
    piecesPerHour:     'Pieces/Hour',
    operatorEfficiency:'Operator Efficiency',
    lineCapacity:      'Line Capacity',
    totalSMV:          'Total SMV Produced',
    workers:           'Workers',
    minutes:           'Minutes (Shift)',
    targetEff:         'Target Efficiency (%)',
    actualPcs:         'Actual Pieces',
    targetPcs:         'Target Pieces',
    hoursDay:          'Hours/Day',
    effResult:         'Efficiency (%)',
    opEffResult:       'Operator Efficiency (%)',
    lineCapResult:     'Line Capacity (pcs/day)',

    fabricConsumption: 'Fabric Consumption',
    cmtCost:           'CMT Cost',
    cmCost:            'CM Cost',
    fabricReqYards:    'Fabric Requirement',
    length:            'Length (cm)',
    width:             'Width (cm)',
    allowance:         'Allowance (cm)',
    gsm:               'GSM',
    cuttingCost:       'Cutting Cost (৳)',
    sewingCost:        'Sewing Cost (৳)',
    finishCost:        'Finishing Cost (৳)',
    fabricCost:        'Fabric Cost (৳)',
    labourCost:        'Labour Cost (৳)',
    overheadCost:      'Overhead Cost (৳)',
    profitPct:         'Profit (%)',
    qtyPcs:            'Quantity (pieces)',
    gsmForFabReq:      'GSM',
    widthYards:        'Width (inches)',
    consumResult:      'Consumption (kg)',
    cmtResult:         'CMT Cost (৳)',
    cmResult:          'Total Cost (৳)',
    fabReqResult:      'Fabric Required (yards)',
    smv:               'SMV (minutes)',
    piecesResult:      'Pieces/Hour',

    dailyTarget:       'Daily Target',
    netProfit:         'Net Profit',
    attendancePct:     'Attendance %',
    minutesProduced:   'Minutes Produced',
    salePrice:         'Sale Price (৳)',
    costPrice:         'Cost Price (৳)',
    presentWorkers:    'Present Workers',
    totalWorkers:      'Total Workers',
    piecesProduced:    'Pieces Produced',
    dailyTgtResult:    'Daily Target (pieces)',
    netProfitResult:   'Net Profit (%)',
    attResult:         'Attendance (%)',
    minsProdResult:    'Minutes Produced',

    // ── TTQC ──────────────────────────────────────────────────────────────
    ttqcTitle:   'TTQC Calculator',
    ttqcDesc2:   'AQL Sampling, Defect Metrics, Quality & Fabric Tests',

    defectTab:     'Defect Metrics',
    qualityQTab:   'Quality Metrics',
    fabricQTab:    'Fabric Tests',

    aqlCalc:      'AQL Sampling',
    defectRate:   'Defect Rate',
    dhuCalc:      'DHU Calculation',
    lotSize:      'Lot Size',
    aqlLevel:     'AQL Level',
    inspLevel:    'Inspection Level',
    sampleSize:   'Sample Size',
    acceptNum:    'Accept Number (Ac)',
    rejectNum:    'Reject Number (Re)',
    defectivePcs: 'Defective Pieces',
    totalInspected:'Total Inspected',
    totalDefects: 'Total Defects',
    defectRateResult:'Defect Rate (%)',
    dhuResult:    'DHU',

    passRate:     'Pass Rate',
    passPcs:      'Pass Pieces',
    totalPcs:     'Total Pieces',
    passRateResult:'Pass Rate (%)',

    weightedDHU:       'Weighted DHU',
    criticalDefects:   'Critical Defects',
    majorDefects:      'Major Defects',
    minorDefects:      'Minor Defects',
    usesInspectedCount:'Uses inspected count from above',
    wDhuResult:        'Weighted DHU',

    auditScore:        'Audit Score',
    defectsFound:      'Defects Found',
    possibleDefects:   'Possible Defects',
    auditResult:       'Audit Score (%)',

    dpmo:              'DPMO',
    sampleSizeDPMO:    'Sample Size',
    defectsFoundD:     'Defects Found',
    dpmoResult:        'DPMO',
    fpyResult:         'First Pass Yield (%)',

    cpkCalc:           'Cpk Calculation',
    sigmaLevel:        'Sigma Level',
    cpkResult:         'Cpk',

    pqCalc:            'PQ Score',
    qualityPoint:      'Quality Point',
    quantityPoint:     'Quantity Point',
    pqResult:          'PQ Score',

    fabric4Point:      'Fabric 4-Point System',
    totalPoints:       'Total Penalty Points',
    yardInspected:     'Yards Inspected',
    fp4Result:         'Points/100yd²',
    fp4GradeResult:    'Grade',

    fabric4PointPer100m:'4-Point per 100m',
    linearYards:        'Linear Yards',
    fabricWidth:        'Fabric Width (inches)',
    fp100mResult:       'Points/100m',

    fabricGradeGSM:    'Fabric Grade by GSM',
    gsmForGrade:        'GSM',
    gsmGradeResult:    'Grade',

    // ── Converter ──
    converterTitle:     'Unit Converter',
    converterDesc2:     'Instant conversions for Length, Weight, Yarn Count, and Temperature',
    lengthTab:          'Length',
    weightTab:          'Weight',
    countTab:           'Yarn Count',
    tempTab:            'Temperature',
    lengthTitle:        'Length Conversion',
    weightTitle:        'Weight Conversion',
    countTitle:         'Yarn Count Conversion',
    tempTitle:          'Temperature Conversion',
    inches:             'Inches (in)',
    yards:              'Yards (yd)',
    meters:             'Meters (m)',
    cm:                 'Centimeters (cm)',
    kg:                 'Kilograms (kg)',
    grams:              'Grams (g)',
    lbs:                'Pounds (lbs)',
    oz:                 'Ounces (oz)',
    celsius:            'Celsius (°C)',
    fahrenheit:         'Fahrenheit (°F)',
    kelvin:             'Kelvin (K)',

    // Footer
    footerDev:      'Developer: Md Rifat (mdrifatdev)',
    footerGithub:   'GitHub: github.com/mdrifatdev',
    footerMade:     'Made for Textile Engineers of Bangladesh 🇧🇩',
    footerVersion:  'v1.0.0',
  },
};
