// TexCalc i18n language file
// To add a new language: add a new key block below and register it in LangContext

export const translations = {
  bn: {
    // App
    appName: 'TexCalc',
    appTagline: 'টেক্সটাইল ইঞ্জিনিয়ারিং ক্যালকুলেটর',

    // Nav
    langToggle: 'EN',
    menu: 'মেনু',

    // Sidebar categories
    home: 'হোম',
    spinning: 'স্পিনিং',
    weaving: 'উইভিং',
    knitting: 'নিটিং',
    dyeing: 'ডাইং',
    garments: 'গার্মেন্টস',
    ttqc: 'টি.টি.কিউ.সি',

    // Home
    heroTitle: 'টেক্সটাইল ইঞ্জিনিয়ারিং ক্যালকুলেটর',
    heroSubtitle: 'স্পিনিং, উইভিং, নিটিং, ডাইং, গার্মেন্টস ও কোয়ালিটি কন্ট্রোলের জন্য পেশাদার ক্যালকুলেটর সমূহ',
    heroNote: 'বাংলাদেশের টেক্সটাইল পেশাদারদের জন্য তৈরি',
    categoriesTitle: 'বিভাগসমূহ',
    spinningDesc: 'কাউন্ট কনভার্সন, টুইস্ট পার ইঞ্চি, টুইস্ট ফ্যাক্টর',
    weavingDesc: 'জিএসএম, রিড কাউন্ট, ক্লথ কভার ফ্যাক্টর',
    knittingDesc: 'জিএসএম ও স্টিচ লেংথ ক্যালকুলেশন',
    dyeingDesc: 'লিকার রেশিও, কেমিক্যাল ডোজিং, সল্ট ক্যালকুলেশন',
    garmentsDesc: 'লাইন এফিশিয়েন্সি, ফ্যাব্রিক কনসাম্পশন, এসএমভি',
    ttqcDesc: 'একিউএল, ডিফেক্ট রেট, ডিএইচইউ ক্যালকুলেশন',

    // Common UI
    calculate: 'হিসাব করুন',
    reset: 'রিসেট',
    result: 'ফলাফল',
    formula: 'সূত্র',
    inputs: 'ইনপুট',
    selectCalculator: 'ক্যালকুলেটর বেছে নিন',
    copied: 'কপি হয়েছে!',
    copy: 'কপি',
    enterValue: 'মান লিখুন',
    calculate_btn: 'ক্যালকুলেট',
    invalidInput: 'অনুগ্রহ করে সঠিক মান দিন',

    // Spinning page
    spinningTitle: 'স্পিনিং ক্যালকুলেটর',
    spinningDesc2: 'সুতার কাউন্ট কনভার্সন, টুইস্ট এবং টুইস্ট ফ্যাক্টর হিসাব করুন',
    countConversion: 'কাউন্ট কনভার্সন',
    tpi: 'টুইস্ট পার ইঞ্চি (TPI)',
    twistFactor: 'টুইস্ট ফ্যাক্টর',
    neCount: 'Ne কাউন্ট',
    texValue: 'Tex মান',
    denierValue: 'Denier মান',
    nmValue: 'Nm মান',
    tpiValue: 'TPI মান',
    tfValue: 'টুইস্ট ফ্যাক্টর',
    countNe: 'কাউন্ট (Ne)',
    tpiInput: 'TPI',
    tfInput: 'টুইস্ট ফ্যাক্টর',

    // Weaving page
    weavingTitle: 'উইভিং ক্যালকুলেটর',
    weavingDesc2: 'জিএসএম, রিড কাউন্ট ও কভার ফ্যাক্টর হিসাব করুন',
    gsmCalc: 'জিএসএম ক্যালকুলেশন',
    reedCount: 'রিড কাউন্ট',
    coverFactor: 'কভার ফ্যাক্টর',
    epi: 'EPI (Ends Per Inch)',
    ppi: 'PPI (Picks Per Inch)',
    warpCount: 'ওয়ার্প কাউন্ট (Ne)',
    weftCount: 'ওয়েফট কাউন্ট (Ne)',
    crimpFactor: 'ক্রিম্প ফ্যাক্টর',
    endsPerDent: 'প্রতি ডেন্টে সুতা সংখ্যা',
    gsmResult: 'জিএসএম',
    reedResult: 'রিড কাউন্ট',
    coverResult: 'কভার ফ্যাক্টর',

    // Knitting page
    knittingTitle: 'নিটিং ক্যালকুলেটর',
    knittingDesc2: 'ফ্যাব্রিকের জিএসএম ও স্টিচ লেংথ হিসাব করুন',
    gsmKnit: 'জিএসএম (নিটিং)',
    stitchLength: 'স্টিচ লেংথ',
    wpi: 'WPI (Wales Per Inch)',
    cpi: 'CPI (Courses Per Inch)',
    sl: 'স্টিচ লেংথ (cm)',
    tex: 'সুতার Tex',
    slResult: 'স্টিচ লেংথ (cm)',
    gsmKnitResult: 'জিএসএম',

    // Dyeing page
    dyeingTitle: 'ডাইং ক্যালকুলেটর',
    dyeingDesc2: 'লিকার রেশিও, কেমিক্যাল ডোজিং ও সল্ট হিসাব করুন',
    liquorRatio: 'লিকার রেশিও',
    chemDosing: 'কেমিক্যাল ডোজিং',
    saltCalc: 'সল্ট ক্যালকুলেশন',
    waterL: 'পানির পরিমাণ (লিটার)',
    fabricKg: 'কাপড়ের ওজন (কেজি)',
    chemPercent: 'কেমিক্যাল % (ওজনের উপর)',
    totalWater: 'মোট পানি (লিটার)',
    requiredSalt: 'প্রয়োজনীয় লবণ (গ্রাম)',
    lrResult: 'লিকার রেশিও',
    chemResult: 'কেমিক্যাল (গ্রাম)',
    saltResult: 'লবণের ঘনত্ব (g/L)',

    // Garments page
    garmentsTitle: 'গার্মেন্টস ক্যালকুলেটর',
    garmentsDesc2: 'লাইন এফিশিয়েন্সি, ফ্যাব্রিক কনসাম্পশন ও এসএমভি হিসাব করুন',
    lineEfficiency: 'লাইন এফিশিয়েন্সি',
    fabricConsumption: 'ফ্যাব্রিক কনসাম্পশন',
    smvToPieces: 'SMV থেকে পিস/ঘন্টা',
    totalSMV: 'মোট উৎপাদিত SMV',
    workers: 'কর্মী সংখ্যা',
    minutes: 'মিনিট (শিফট)',
    targetEff: 'টার্গেট এফিশিয়েন্সি (%)',
    length: 'দৈর্ঘ্য (cm)',
    width: 'প্রস্থ (cm)',
    allowance: 'অ্যালাউন্স (cm)',
    gsm: 'জিএসএম',
    smv: 'SMV',
    effResult: 'এফিশিয়েন্সি (%)',
    consumResult: 'কনসাম্পশন (kg)',
    piecesResult: 'পিস/ঘন্টা',

    // TTQC page
    ttqcTitle: 'টি.টি.কিউ.সি ক্যালকুলেটর',
    ttqcDesc2: 'একিউএল টেবিল, ডিফেক্ট রেট ও ডিএইচইউ হিসাব করুন',
    aqlCalc: 'AQL ডিফেক্ট লিমিট',
    defectRate: 'ডিফেক্ট রেট (%)',
    dhuCalc: 'DHU ক্যালকুলেশন',
    lotSize: 'লট সাইজ',
    aqlLevel: 'AQL লেভেল',
    sampleSize: 'স্যাম্পল সাইজ',
    acceptNum: 'গ্রহণযোগ্য সংখ্যা (Ac)',
    rejectNum: 'প্রত্যাখ্যাত সংখ্যা (Re)',
    defectivePcs: 'ডিফেক্টিভ পিস',
    totalInspected: 'মোট পরীক্ষিত পিস',
    totalDefects: 'মোট ডিফেক্ট সংখ্যা',
    defectRateResult: 'ডিফেক্ট রেট (%)',
    dhuResult: 'DHU',

    // Footer
    footerText: '© ২০২৬ TexCalc — Md. Rifat Aslam কর্তৃক নির্মিত',
  },

  en: {
    // App
    appName: 'TexCalc',
    appTagline: 'Textile Engineering Calculator',

    // Nav
    langToggle: 'বাং',
    menu: 'Menu',

    // Sidebar categories
    home: 'Home',
    spinning: 'Spinning',
    weaving: 'Weaving',
    knitting: 'Knitting',
    dyeing: 'Dyeing',
    garments: 'Garments',
    ttqc: 'TTQC',

    // Home
    heroTitle: 'Textile Engineering Calculator',
    heroSubtitle: 'Professional calculators for Spinning, Weaving, Knitting, Dyeing, Garments & Quality Control',
    heroNote: 'Built for Textile Professionals of Bangladesh',
    categoriesTitle: 'Categories',
    spinningDesc: 'Count Conversion, Twist Per Inch, Twist Factor',
    weavingDesc: 'GSM, Reed Count, Cloth Cover Factor',
    knittingDesc: 'GSM & Stitch Length Calculation',
    dyeingDesc: 'Liquor Ratio, Chemical Dosing, Salt Calculation',
    garmentsDesc: 'Line Efficiency, Fabric Consumption, SMV',
    ttqcDesc: 'AQL, Defect Rate, DHU Calculation',

    // Common UI
    calculate: 'Calculate',
    reset: 'Reset',
    result: 'Result',
    formula: 'Formula',
    inputs: 'Inputs',
    selectCalculator: 'Select Calculator',
    copied: 'Copied!',
    copy: 'Copy',
    enterValue: 'Enter value',
    calculate_btn: 'Calculate',
    invalidInput: 'Please enter valid values',

    // Spinning page
    spinningTitle: 'Spinning Calculator',
    spinningDesc2: 'Calculate yarn count conversion, twist and twist factor',
    countConversion: 'Count Conversion',
    tpi: 'Twist Per Inch (TPI)',
    twistFactor: 'Twist Factor',
    neCount: 'Ne Count',
    texValue: 'Tex Value',
    denierValue: 'Denier Value',
    nmValue: 'Nm Value',
    tpiValue: 'TPI Value',
    tfValue: 'Twist Factor',
    countNe: 'Count (Ne)',
    tpiInput: 'TPI',
    tfInput: 'Twist Factor',

    // Weaving page
    weavingTitle: 'Weaving Calculator',
    weavingDesc2: 'Calculate GSM, Reed Count and Cover Factor',
    gsmCalc: 'GSM Calculation',
    reedCount: 'Reed Count',
    coverFactor: 'Cover Factor',
    epi: 'EPI (Ends Per Inch)',
    ppi: 'PPI (Picks Per Inch)',
    warpCount: 'Warp Count (Ne)',
    weftCount: 'Weft Count (Ne)',
    crimpFactor: 'Crimp Factor',
    endsPerDent: 'Ends Per Dent',
    gsmResult: 'GSM',
    reedResult: 'Reed Count',
    coverResult: 'Cover Factor',

    // Knitting page
    knittingTitle: 'Knitting Calculator',
    knittingDesc2: 'Calculate fabric GSM and stitch length',
    gsmKnit: 'GSM (Knitting)',
    stitchLength: 'Stitch Length',
    wpi: 'WPI (Wales Per Inch)',
    cpi: 'CPI (Courses Per Inch)',
    sl: 'Stitch Length (cm)',
    tex: 'Yarn Tex',
    slResult: 'Stitch Length (cm)',
    gsmKnitResult: 'GSM',

    // Dyeing page
    dyeingTitle: 'Dyeing Calculator',
    dyeingDesc2: 'Calculate Liquor Ratio, Chemical Dosing and Salt',
    liquorRatio: 'Liquor Ratio',
    chemDosing: 'Chemical Dosing',
    saltCalc: 'Salt Calculation',
    waterL: 'Water Amount (Liters)',
    fabricKg: 'Fabric Weight (kg)',
    chemPercent: 'Chemical % (on weight)',
    totalWater: 'Total Water (Liters)',
    requiredSalt: 'Required Salt (grams)',
    lrResult: 'Liquor Ratio',
    chemResult: 'Chemical (grams)',
    saltResult: 'Salt Concentration (g/L)',

    // Garments page
    garmentsTitle: 'Garments Calculator',
    garmentsDesc2: 'Calculate Line Efficiency, Fabric Consumption and SMV',
    lineEfficiency: 'Line Efficiency',
    fabricConsumption: 'Fabric Consumption',
    smvToPieces: 'SMV to Pieces/Hour',
    totalSMV: 'Total SMV Produced',
    workers: 'Number of Workers',
    minutes: 'Minutes (Shift)',
    targetEff: 'Target Efficiency (%)',
    length: 'Length (cm)',
    width: 'Width (cm)',
    allowance: 'Allowance (cm)',
    gsm: 'GSM',
    smv: 'SMV',
    effResult: 'Efficiency (%)',
    consumResult: 'Consumption (kg)',
    piecesResult: 'Pieces/Hour',

    // TTQC page
    ttqcTitle: 'TTQC Calculator',
    ttqcDesc2: 'AQL Table, Defect Rate and DHU calculations',
    aqlCalc: 'AQL Defect Limit',
    defectRate: 'Defect Rate (%)',
    dhuCalc: 'DHU Calculation',
    lotSize: 'Lot Size',
    aqlLevel: 'AQL Level',
    sampleSize: 'Sample Size',
    acceptNum: 'Accept Number (Ac)',
    rejectNum: 'Reject Number (Re)',
    defectivePcs: 'Defective Pieces',
    totalInspected: 'Total Inspected',
    totalDefects: 'Total Defects',
    defectRateResult: 'Defect Rate (%)',
    dhuResult: 'DHU',

    // Footer
    footerText: '© 2026 TexCalc — Built by Md. Rifat Aslam',
  },
};
